
[workspace]
resolver = "2"

members = [
    "gengar_engine",
    "gengar_render_opengl",
    "gengar_renderapi_opengl_windows",

    "gengar_platform_windows",
    "gengar_platform_web",

    "pack_world_game", 
]
