[package]
name = "elara_render_opengl"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/elara_render_opengl.rs"

[dependencies]

elara_engine = { git = "https://github.com/RyanRothweiler/elara_engine.git", branch = "version/1.x.x", version = "=1.0.0" }
libc = "0.2.155"

