[package]
name = "pack_world_game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/game.rs"

[dependencies]
gengar_engine = { path = "../gengar_engine" }
gengar_render_opengl = { path = "../gengar_render_opengl" }
rand = "0.9.0"

[features]
default = ["dev"]
dev = []