[package]
name = "pack_world_game"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/game.rs"

[dependencies]
elara_engine = { path = "../elara_engine" }
gengar_render_opengl = { path = "../gengar_render_opengl" }

[dev-dependencies]
rand = "0.9.0"